### ISSUE TITLE
Put ".fxml"- and properties-files into source folder like in afterburner.fx

### ISSUE THREAD

**Issue by haisi** [thomasdarimont/spring-labs#4]
I cloned the "spring-boot-javafx-jpa-demo" and tried to put the `.fxml`-, `.css`\- and `.properties`-files into the source folder under `demo.project.ui`, but then the `resource`-object is null.  
I compared your `AbstractFxmlView.java`-class with afterburner.fx's `FXMLView.java`-class and it seems that your implementation loads the resource the same way. So why doesn't it work this way? 
Do you know how I can solve this issue?

**Comment by thomasdarimont** [comment]
Hi @haisi,

If you want to do that you have to configure the maven build to consider those resources in src/main/java see:
https://github.com/AdamBien/afterburner.fx/blob/02f25fdde9629fcce50ea8ace5dec4f802958c8d/pom.xml#L154

Since those files are actually resources I'd thought the would be better plaved in src/main/resources - although this requires a parallel folder hierarchy that may be a bit cumbersome to work with during refactoring etc... may be this is enough reasoning for putting it in src/main/java I'll give it a spin.

Thanks for your comments!

Cheers,
Thomas

**Comment by haisi** [comment]
Thanks, works like a charm.  

Btw. nice little project but a maven archetype for an example project and a maven dependency for the `AbstractJavaFxApplicationSupport.java`\- and the `AbstractFxmlView`-class (like for afterburner.fx) would be nice.  

Best regards
haisi
